### ISSUE TITLE
macos, shell integration error 

### ISSUE THREAD

**Issue by kulfix** [RooVetGit/Roo-Code#237]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

not important

### What happened?

no_shell_integration received for terminal 1
extensionHostProcess.js:163
rejected promise not handled within 1 second: TimeoutError: Promise timed out after 4000 milliseconds
extensionHostProcess.js:163
stack trace: TimeoutError: Promise timed out after 4000 milliseconds
	at /Users/clpik/.vscode/extensions/rooveterinaryinc.roo-cline-2.2.33/dist/extension.js:747:5977
	at new Promise (<anonymous>)
	at EEe (/Users/clpik/.vscode/extensions/rooveterinaryinc.roo-cline-2.2.33/dist/extension.js:747:5610)
	at Bd (/Users/clpik/.vscode/extensions/rooveterinaryinc.roo-cline-2.2.33/dist/extension.js:747:6787)
	at Oae.runCommand (/Users/clpik/.vscode/extensions/rooveterinaryinc.roo-cline-2.2.33/dist/extension.js:1002:1736)
	at vK.executeCommandTool (/Users/clpik/.vscode/extensions/rooveterinaryinc.roo-cline-2.2.33/dist/extension.js:2156:605)
	at runNextTicks (node:internal/process/task_queues:60:5)
	at listOnTimeout (node:internal/timers:545:9)
	at process.processTimers (node:internal/timers:519:7)
	at async vK.presentAssistantMessage (/Users/clpik/.vscode/extensions/rooveterinaryinc.roo-cline-2.2.33/dist/extension.js:2220:870)

### Steps to reproduce

1. run shell-integration-problems
2. any command run
3.

**Comment by rvion** [comment]
probably related to https://github.com/cline/cline/issues/1146

**Comment by hannesrudolph** [comment]
Closing for newer issue with more info related to repro steps.
